### ISSUE TITLE
Digispark show up as an "Unknown Device" in the Device Manager after running this code for a while .

### ISSUE THREAD

**Issue by flakka2022** [mcore1976/jammer#2]
### **I have four different types of Digispark boards, including fake and original ones. Initially, everything worked fine, but suddenly they stopped working ( in one or two week this happened and was not damage of heat or anything visually detectable ) . When I connect the Digispark boards to my computer, they show up as "Unknown Device" in the Device Manager. While I bought another Digispark, which works fine after installing drivers correctly, the other boards still show up as Unknown Device. I am wondering how to fix this issue. Could it be caused by heavy jammer code that the Digispark Attiny cannot handle or execute?** 
**However, it's worth mentioning that the "Unknown Device" Digisparks still work fine for jamming ( not one of the old ones ) .
I would appreciate it if someone could take time and help me resolve this issue and make boards programable again .
The error message in the device manager properties is: 
'Windows has stopped this device because it has reported problems. (Code 43)
 A request for the USB device descriptor failed.'**

**Comment by mcore1976** [comment]
this is a known issue , because Digispark emulates USB port behavior by the software sometimes it has problems with connection to the PC. This is not a fult of my jammer code.  
Browse following  threads :
http://digistump.com/board/index.php?topic=3267.0
 http://digistump.com/board/index.php?topic=2501.0
https://cyberblogspot.com/digispark-usb-device-not-recognized/

You may also try connecting the Digispark through USB cable extender, USB hub (mostly helps), use different USB port or even different PC. 

Alternatively you may use different Arduino board, since the code should be portable and work on any other boards (just change PIN number for FS1000A interconnection)

**Comment by flakka2022** [comment]
thank you for reply .
